name: blue_controller_companion
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  flutter_secure_storage: ^4.2.1
  envied: ^0.5.4+1
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  flex_color_scheme: ^7.3.1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  gap: ^3.0.1
  pretty_dio_logger: ^1.3.1
  flutter_blue_plus: ^1.32.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  go_router_builder: ^2.7.0
  build_verify: ^3.1.0
  flutter_gen_runner: ^5.6.0
  envied_generator: ^0.5.4+1
  retrofit_generator: ^8.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"
  
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
